version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: bilzadb:latest
    environment: 
      - MYSQL_DATABASE=bilzadb
      - MYSQL_ROOT_PASSWORD=bils32611

    